# Use root/example user/password credentials
version: '3.1'

networks:
  php-db-bridge:

volumes:
  mariadb-data:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - php-db-bridge
    volumes:
      - ./src:/var/www/html/

  db:
    platform: linux/x86_64
    image: mariadb:10.6.4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: company1
      MARIADB_USER: php
      MARIADB_PASSWORD: secret123
    networks:
      - php-db-bridge
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - php-db-bridge
